apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - route-frontend.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      environment: openshift
    includeSelectors: false
