#FROM golang:alpine as build
FROM registry.redhat.io/ubi9/go-toolset as build

WORKDIR /opt/app-root
ENV GOPATH=/opt/app-root/
COPY src src
WORKDIR /opt/app-root/src/app-api/
      
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/app-api


#FROM scratch
FROM registry.redhat.io/ubi9/ubi-minimal

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /tmp/app-api /usr/bin/app-api

USER 1001

EXPOSE 8080
CMD ["/usr/bin/app-api"]
ENTRYPOINT ["/usr/bin/app-api"]
