#FROM golang:alpine as build
FROM registry.redhat.io/ubi9/go-toolset as build

WORKDIR /opt/app-root
ENV GOPATH=/opt/app-root/
COPY src src
WORKDIR /opt/app-root/src/webapp/
      
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/webapp


#FROM scratch
FROM registry.redhat.io/ubi9/ubi-minimal

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /tmp/webapp /usr/bin/webapp
COPY src/webapp/html /opt/app-root/html

ENV HTML_DIR=/opt/app-root/html

USER 1001

EXPOSE 8080
CMD ["/usr/bin/webapp"]
ENTRYPOINT ["/usr/bin/webapp"]
