#FROM golang:alpine as build
FROM registry.redhat.io/ubi9/go-toolset as build

WORKDIR /opt/app-root
ENV GOPATH=/opt/app-root/
COPY src src
WORKDIR /opt/app-root/src/dbapi/
      
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o /tmp/dbapi


FROM registry.redhat.io/ubi9-minimal
#FROM scratch

COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /tmp/dbapi /usr/bin/dbapi

USER 1001

EXPOSE 8080
CMD ["/usr/bin/dbapi"]
ENTRYPOINT ["/usr/bin/dbapi"]
