apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: carinfo

labels:
  - pairs:
      app.kubernetes.io/part-of: carinfo
    includeSelectors: false

resources:
  - mariadb/pvc.yaml
  - mariadb/deployment.yaml
  - mariadb/service.yaml
  - dbapi/deployment.yaml
  - dbapi/service.yaml
  - app-api/deployment.yaml
  - app-api/service.yaml
  - webapp/deployment.yaml
  - webapp/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml

images:
  - name: quay.io/ooichman/carinfo/frontend
    newTag: latest
  - name: quay.io/ooichman/carinfo/app-api
    newTag: latest
  - name: quay.io/ooichman/carinfo/dbapi
    newTag: latest
  - name: quay.io/ooichman/carinfo/webapp
    newTag: latest
