apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
      - image: quay.io/ooichman/carinfo/frontend:latest
        name: carinfo-frontend
        ports:
        - containerPort: 8080
        env:
        - name: DBAPI_URL
          value: 'http://dbapi:8080/query'
        - name: PORT
          value: "8080"
