apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  ports:
  - name: frontend
    port: 8080
    targetPort: 8080
  - name: frontend-ssl
    port: 8443
    targetPort: 8443
  selector:
    app: frontend
